#
# HandItemHide Config File
# Config ver : 1.0
#

#メッセージ関係
MSG:
  flyOn: "&6飛行状態を有効にしました"
  flyOff: "&9飛行状態を解除しました"
  NoPex: "&4権限がありません"
  Login: "&6%player &bがログインしました。"
  Logout: "&6%player &bがログアウトしました。"
  Reload: "&aConfigをリロードしました。"

#ログイン,ログアウトのメッセージの有無
#偽装ではなく、サーバに入ったとき、抜けたときに表示されるものです。
LoginMessage: true
LogoutMessage: true

#ログインとログアウトの偽造の有無
#def : true
FakeMessage: true
#アップデート通知
#def : true
Update: true