name: HandItemHide
version: ${project.version}
main: me.yama2211.hih.Main

commands:
  sp:
    description: sp.use
    usage: /sp on or off
  sp.reload:
    description: sp.reload
    usage: /sp reload